### create user (username, password?, role? : "CLIENT" | "ADMIN" [CLIENT if not specified])
### this id: 7c873cf9-6644-4b07-b1da-9865291c4774
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "adm",
  "password": "administrator",
  "role": "ADMIN"
}

### this id: 7c873cf9-6644-4b07-b1da-9865291c4774
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "adm",
  "password": "administrator"
}

### this id: 7c873cf9-6644-4b07-b1da-9865291c4774
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZWVjMWNmOC03MWY0LTRiM2QtOGJlZS1hNDNkMWIwZmUwMDkiLCJ1c2VybmFtZSI6ImFkbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY4NzE2OTYxMCwiZXhwIjoxNjg3MTcwNTEwfQ.UlANcI9EBg5rqL4B5sp9x2SsKtI3MtsPUA6eY4UCte8
### this id: 7c873cf9-6644-4b07-b1da-9865291c4774
POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZWVjMWNmOC03MWY0LTRiM2QtOGJlZS1hNDNkMWIwZmUwMDkiLCJ1c2VybmFtZSI6ImFkbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY4NzE2OTYxMCwiZXhwIjoxNjg3MTcwNTEwfQ.UlANcI9EBg5rqL4B5sp9x2SsKtI3MtsPUA6eY4UCte8
### create ingredient-categories (name)
### this id: 580a8e7c-e7f4-495f-8f44-2d049dc36dfb
POST http://localhost:3000/ingredient-categories
Content-Type: application/json

{
  "name": "legume"
}

### create ingredients (name, categoryId)
### this id: 96bbbdc4-5373-403d-aa42-961d97ece3cd
POST http://localhost:3000/ingredients
Content-Type: application/json

{
  "name":"carrot",
  "categoryId":"580a8e7c-e7f4-495f-8f44-2d049dc36dfb"
}

### create menus categories (name)
### this id: 55658d89-c536-445a-a3c5-94f9b9c8d349
POST http://localhost:3000/menus-categories
Content-Type: application/json

{
  "name": "vegane meals"
}

### create menus (name, menusCategoriesID)
### this id: de6a25ce-bebd-4b67-ad8a-56ab944e4c99
POST http://localhost:3000/menus
Content-Type: application/json

{
  "name": "only legumes",
  "menusCategoriesId": "55658d89-c536-445a-a3c5-94f9b9c8d349"

}

### create dish categories (name)
### this id: 20cfa3d1-a85c-46d3-b4d4-9ee227ad71b7
POST http://localhost:3000/dish-categories
Content-Type: application/json

{
  "name": "vegane"
}

###
GET http://localhost:3000/invoices?

### create dishes (name, price, ingredients, dishCategoriesId, menusId)
### this id: 8afd4769-78e3-420c-bddf-b1f7b45c03c4
POST http://localhost:3000/dishes
Content-Type: application/json

{
  "name": "karoty tout court",
  "price": 1000,
  "ingredients":[{"id":"96bbbdc4-5373-403d-aa42-961d97ece3cd"}],
  "dishCategoriesId": "20cfa3d1-a85c-46d3-b4d4-9ee227ad71b7",
  "menusId": "de6a25ce-bebd-4b67-ad8a-56ab944e4c99"
}

### create order items (quantity, dishId (single))
### this id: fc70f04d-3438-4d89-9a04-5d4c144447d5
POST http://localhost:3000/order-items
Content-Type: application/json

{
  "quantity": 2,
  "dishesId" : "8afd4769-78e3-420c-bddf-b1f7b45c03c4"
}

### create orders (order items)
### this id: c15468f8-0d93-4482-a8b0-e42e731ddcad
POST http://localhost:3000/orders
Content-Type: application/json

{
  "items":[{"id":"fc70f04d-3438-4d89-9a04-5d4c144447d5"}]
}

### create invoices (usersId and orders)
### this id: c45fea8d-e8dc-40fd-94bb-f677f771576e
POST http://localhost:3000/invoices
Content-Type: application/json

{
  "usersId":"7c873cf9-6644-4b07-b1da-9865291c4774",
  "orders":[{"id":"c15468f8-0d93-4482-a8b0-e42e731ddcad"}]
}
